apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: nestjs-api-prod:1.0.0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - yarn cron:cronjob
          restartPolicy: OnFailure
